### ISSUE TITLE
Removing a CA section in usecases doc understates the occurrence of distrust events

### ISSUE THREAD

**Issue by nharper** [dennisjackson/trust-negotiation-comments#1]
Recent CA distrust events include [Camerfirma](https://groups.google.com/g/mozilla.dev.security.policy/c/PnAAWnxyosM/m/6L-ERa9CAQAJ) (2021), [TrustCor](https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/oxX69KFvsm4/m/PKpJf5W6AQAJ) (2022), [e-Tugra](https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A/m/dy9YLbuuAgAJ) (2023), [e-commerce monitoring](https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI/m/H-I5V183AQAJ) (2024). This is not "around the order of one per decade".

**Comment by dennisjackson** [comment]
This section is about the distrust of major CAs as described in the opening sentence: 

> From time to time, it emerges that a major CA

The distrust of small-scale CAs is already a non-issue. However, I've updated the text to make this clearer.
