### ISSUE TITLE
Server burden due to divergence is not accurately described

### ISSUE THREAD

**Issue by dadrian** [dennisjackson/trust-negotiation-comments#12]
In ["Divergence and Fragmentation"](concerns-and-risks.md#divergence-and-fragmentation) in the Risks document:

> This also means root programs can diverge arbitrarily in their requirements, fragmenting the PKI and placing a much greater burden on website operators and CAs to obtain a bundle of certificates satisfactory to the diverging requirements of the various root programs.

Servers currently have a burden from divergence in the form of an intersection problem—they need to find a single certificate that can be used for all clients that use a single algorithm, or implement a multi-certificate model using inaccurate and complex fingerprinting methods that are only suitable for technically sophisticated server operators (e.g. modern hosting providers). 

Given existing divergence in root store contents, and temporal divergence across versions of root stores, solving the intersection problem is already difficult for servers that require broad compatibility across a set of diverse devices and clients. It is not accurate to say that it is a greater burden on server operators to be able to accurately serve, e.g. one certificate to modern clients and one certificate to older clients, than it is to solve the intersection problem by identifying a (possibly nonexistent) certificate that works with all devices.

To make a strong statement about which case is a greater burden requires speculation far outside the scope of an Internet draft, and is specific to the needs of individual servers and the capabilities of the clients those servers desire to support.

**Comment by dennisjackson** [comment]
See the discussion on older devices in the Usecases document.

**Comment by nharper** [comment]
The discussion in the "Handling Older Clients" section of the usecases document doesn't address the burden that currently exists on server operators (and will continue to exist on server operators). The risks document is making a claim about "placing a much greater burden on website operators" without appropriately comparing it to the existing burden. The risks document either needs to accurately describe and compare the burden of the intersection problem (in a world without trust negotiation) to the burden of serving multiple certificates to be able to make such a claim, or the argument about burden on server operators needs to be struck from the risks document.

**Comment by dennisjackson** [comment]
Feel free to open a new issue explaining the existing burden. I am unaware of any website struggling with this issue presently. A concrete example would be most useful.
