### ISSUE TITLE
Root Program and Mass Surveillance section inaccurately describes balkanization

### ISSUE THREAD

**Issue by dadrian** [dennisjackson/trust-negotiation-comments#13]
The ["Root Programs and Mass Surveillance"](concerns-and-risks.md#root-programs-and-mass-surveillance) section makes an obviously contradictory claim:

> Trust Expressions enables these different root programs to co-exist, with websites having certificate chains from many domestic root programs to maintain availability in each country, effectively dividing and balkanizing the web. This end-state is impossible without a design for trust negotiation like Trust Expressions or Trust Anchors.

The web cannot be simultaneously balkanized and divided per-country, but also available across all countries.

**Comment by dennisjackson** [comment]
~web~ WebPKI
