### ISSUE TITLE
Handling Older Clients section conflates security updates with root store updates

### ISSUE THREAD

**Issue by nharper** [dennisjackson/trust-negotiation-comments#3]
> The EU and the UK already have laws that require all device manufacturers to offer security updates for the full lifetime of the device, ensuring manufacturers keep device’s root stores updated.

The security updates that the EU and UK laws require are updates to fix vulnerabilities in the product. Depending on the device, a failure to update the root store would be a functional issue, not a vulnerability, e.g. a set-top box unable to connect to media sources or a printer unable to fetch print jobs.

**Comment by dennisjackson** [comment]
Actually the EU act is a duty of care for the entire product lifecycle. It is not scoped purely to security updates, although it does include them. 

Please read the [summary of the act](https://digital-strategy.ec.europa.eu/en/policies/cyber-resilience-act) which I linked in the document.

**Comment by nharper** [comment]
I read the summary of the act, but it is too high level to make reasonable assumptions from. Hence I've been referring to the text of the act instead. Where in [the act](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex:52022PC0454) does it require the duty of care for the entire product lifecycle? Is "duty of care" a term of art or otherwise defined in the act? What does the act define as the entire product lifecycle?

Regardless of those questions, the usecases doc mentions laws about security updates, not about duty of care, and then makes the unsupported conclusion that manufacturers will keep root stores updated. Further, absent market pressures to keep devices updated (either regulatory or reputational), manufacturers will keep costs low and not provide updates. The laws cited in the "Handling Older Clients" section do not support a conclusion that devices will be kept up to date and thus not be a problem.

**Comment by dennisjackson** [comment]
Already answered with a direct citation of the law in https://github.com/dennisjackson/trust-negotiation-comments/issues/2#issuecomment-2241451520

**Comment by nharper** [comment]
The phrase "duty of care" does not appear in [the text](https://www.europarl.europa.eu/doceo/document/TA-9-2024-0130_EN.html) (link from https://github.com/dennisjackson/trust-negotiation-comments/issues/2#issuecomment-2241451520). Please cite where the CRA would require that root stores also be kept updated for the lifetime of the product, keeping in mind that updating root stores is separate from providing security updates.

**Comment by dennisjackson** [comment]
I'm comfortable quoting the EU Commission's official [description](https://digital-strategy.ec.europa.eu/en/policies/cyber-resilience-act) of what the act contains: 

> The Cyber Resilience Act will guarantee: [...] an obligation to provide duty of care for the entire lifecycle of such products.

If you disagree, feel free to rebut it with citation of where you think the legal text falls short.

**Comment by nharper** [comment]
> (2)  This Regulation aims to set the boundary conditions for the development of secure products with digital elements by ensuring that hardware and software products are placed on the market with fewer vulnerabilities and that manufacturers take security seriously throughout a product’s lifecycle.

The regulation is about decreasing vulnerabilities and taking security seriously. That sounds like a duty of care **with respect to security**, not a broad duty of care encompassing all aspects of the product.

Providing a citation to where a text does not say something is a fools errand which I will not run.
